apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk
  labels: 
    app:  elk

spec:
  selector:
    matchLabels:
      project: elk
  template:
    metadata:
      labels:
        project: elk
    spec:
      containers:

      - name: kibana
        image: kibana:7.5.2
        ports:
        - containerPort: 5601
        env:
        - name: SERVER_NAME
          value: "kibana"

      - name: elasticsearch
        image: elasticsearch:7.5.2
        ports:
        - containerPort: 9200
        env:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: discovery.type
            value: single-node