---
- name: add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  register: dockerrepo

- name: update yum ca—Åhe
  yum:
    update_cache: true
  when: dockerrepo.changed

- name: Install a list of docker packages 
  yum:
    name:
      - containerd.io
      - docker-ce
    state: present

- name: Start and enable service docker
  service:
    name: docker
    state: started
    enabled: yes